// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: mw/grpcmw/internal/test.proto

package internal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestServiceClient is the client API for TestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestServiceClient interface {
	GetCtxId(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextId, error)
	GetCtxIdStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TestService_GetCtxIdStreamClient, error)
}

type testServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTestServiceClient(cc grpc.ClientConnInterface) TestServiceClient {
	return &testServiceClient{cc}
}

func (c *testServiceClient) GetCtxId(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ContextId, error) {
	out := new(ContextId)
	err := c.cc.Invoke(ctx, "/mw.grpcmw.internal.TestService/GetCtxId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *testServiceClient) GetCtxIdStream(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (TestService_GetCtxIdStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &TestService_ServiceDesc.Streams[0], "/mw.grpcmw.internal.TestService/GetCtxIdStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &testServiceGetCtxIdStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TestService_GetCtxIdStreamClient interface {
	Recv() (*ContextId, error)
	grpc.ClientStream
}

type testServiceGetCtxIdStreamClient struct {
	grpc.ClientStream
}

func (x *testServiceGetCtxIdStreamClient) Recv() (*ContextId, error) {
	m := new(ContextId)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TestServiceServer is the server API for TestService service.
// All implementations must embed UnimplementedTestServiceServer
// for forward compatibility
type TestServiceServer interface {
	GetCtxId(context.Context, *emptypb.Empty) (*ContextId, error)
	GetCtxIdStream(*emptypb.Empty, TestService_GetCtxIdStreamServer) error
	mustEmbedUnimplementedTestServiceServer()
}

// UnimplementedTestServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTestServiceServer struct {
}

func (UnimplementedTestServiceServer) GetCtxId(context.Context, *emptypb.Empty) (*ContextId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCtxId not implemented")
}
func (UnimplementedTestServiceServer) GetCtxIdStream(*emptypb.Empty, TestService_GetCtxIdStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method GetCtxIdStream not implemented")
}
func (UnimplementedTestServiceServer) mustEmbedUnimplementedTestServiceServer() {}

// UnsafeTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestServiceServer will
// result in compilation errors.
type UnsafeTestServiceServer interface {
	mustEmbedUnimplementedTestServiceServer()
}

func RegisterTestServiceServer(s grpc.ServiceRegistrar, srv TestServiceServer) {
	s.RegisterService(&TestService_ServiceDesc, srv)
}

func _TestService_GetCtxId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestServiceServer).GetCtxId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mw.grpcmw.internal.TestService/GetCtxId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestServiceServer).GetCtxId(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _TestService_GetCtxIdStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TestServiceServer).GetCtxIdStream(m, &testServiceGetCtxIdStreamServer{stream})
}

type TestService_GetCtxIdStreamServer interface {
	Send(*ContextId) error
	grpc.ServerStream
}

type testServiceGetCtxIdStreamServer struct {
	grpc.ServerStream
}

func (x *testServiceGetCtxIdStreamServer) Send(m *ContextId) error {
	return x.ServerStream.SendMsg(m)
}

// TestService_ServiceDesc is the grpc.ServiceDesc for TestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mw.grpcmw.internal.TestService",
	HandlerType: (*TestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCtxId",
			Handler:    _TestService_GetCtxId_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetCtxIdStream",
			Handler:       _TestService_GetCtxIdStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mw/grpcmw/internal/test.proto",
}
